import React, { useState, useEffect, useRef } from 'react';
import { PanelCard, ConfirmationModal } from '../components/ui';
// FIX: Import missing functions for agent DB management.
import { resetTableSequence, resetTableData, fetchTableDetails, resetAgentTableSequence, resetAgentTableData } from '../services/dataManagementService';
import type { TableDetails } from '../types';
import TableDetailsView from '../components/settings/TableDetailsView';
import { Database, AlertTriangle, RefreshCw, Trash2, Table, MoreVertical, Info } from 'lucide-react';
import ReactDOM from 'react-dom';
import ApiKeyManagerCard from '../components/settings/ApiKeyManagerCard';

interface TableInfo {
    name: string;
    description: string;
    disableSequenceReset?: boolean;
}

interface DatabaseGroup {
    dbName: 'Main App' | 'Agent';
    tables: TableInfo[];
}

const databases: DatabaseGroup[] = [
    {
        dbName: 'Main App',
        tables: [
            { name: 'ai_api_keys', description: "Stores and manages Gemini API keys for the AI Assistant." },
            { name: 'ai_chat_history', description: "Stores the full history of all AI Assistant conversations." },
            { name: 'article_conversations', description: "Links conversations to specific news articles that were discussed.", disableSequenceReset: true },
            { name: 'conversations', description: "Primary storage for all user conversations with the AI.", disableSequenceReset: true },
            { name: 'ltm', description: "Stores long-term memory facts generated by the AI for each user.", disableSequenceReset: true },
            { name: 'profiles', description: "Core user profile information, linked to authentication.", disableSequenceReset: true },
            { name: 'public_article_cache', description: "Stores cached article content to speed up retrieval.", disableSequenceReset: true },
            { name: 'public_content', description: "General-purpose public content for the application." },
            { name: 'public_news_articles', description: "The main table for all published and user-visible news articles." },
            { name: 'update_news_config', description: "Configuration for the news update function.", disableSequenceReset: true },
            { name: 'update_news_logs', description: "Logs for the periodic 'update_news' function runs." },
            { name: 'user_article_interactions', description: "Tracks user likes, views, and bookmarks on news articles.", disableSequenceReset: true },
            { name: 'user_settings', description: "Contains individual user preferences and configurations.", disableSequenceReset: true },
        ]
    },
    {
        dbName: 'Agent',
        tables: [
            { name: 'groq_agent_logs', description: "Logs for the Groq agent function runs." },
        ]
    }
];

const ActionPopover: React.FC<{
    anchorEl: HTMLElement | null;
    onClose: () => void;
    children: React.ReactNode;
}> = ({ anchorEl, onClose, children }) => {
    const popoverRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (popoverRef.current && !popoverRef.current.contains(event.target as Node)) {
                onClose();
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [onClose]);

    if (!anchorEl) return null;

    const rect = anchorEl.getBoundingClientRect();
    const style: React.CSSProperties = {
        position: 'absolute',
        top: `${rect.bottom + window.scrollY + 4}px`,
        left: `${rect.left + window.scrollX}px`,
        transform: 'translateX(-85%)',
    };

    return ReactDOM.createPortal(
        <div ref={popoverRef} style={style} className="z-50 w-48">
            <div className="custom-dropdown-panel open !static !opacity-100 !transform-none">
                {children}
            </div>
        </div>,
        document.body
    );
};


const SettingsPage: React.FC = () => {
    const [selectedView, setSelectedView] = useState<'db' | 'keys'>('db');
    const [selectedTable, setSelectedTable] = useState('profiles');
    const [modal, setModal] = useState<{ type: 'sequence' | 'data' | null; tableName: string | null }>({ type: null, tableName: null });
    const [isLoading, setIsLoading] = useState(false);
    const [confirmationInput, setConfirmationInput] = useState('');
    const [activePopover, setActivePopover] = useState<{ tableName: string; anchorEl: HTMLElement } | null>(null);
    const [tableDetails, setTableDetails] = useState<TableDetails | null>(null);
    const [isFetchingDetails, setIsFetchingDetails] = useState(false);
    
    // Refs for the connecting line
    const selectedTableRef = useRef<HTMLDivElement>(null);
    const tableListContainerRef = useRef<HTMLDivElement>(null);
    const detailsContainerRef = useRef<HTMLDivElement>(null);
    // Ref for the SVG path elements to update them imperatively, avoiding React re-renders on scroll.
    const headerLinePathRef = useRef<SVGPathElement>(null);
    const rowLinesGroupRef = useRef<SVGGElement>(null);


    const allTables = databases.flatMap(db => db.tables.map(t => ({ ...t, dbName: db.dbName })));
    const selectedTableInfo = allTables.find(t => t.name === selectedTable);
    
    // Effect to calculate and draw the connecting line
    useEffect(() => {
        if (selectedView !== 'db') return; // Only draw lines for DB view
        // Imperatively update the SVG path to prevent re-renders during scroll, ensuring max performance.
        const updateConnectingLines = () => {
            const startElement = selectedTableRef.current;
            const endHeaderElement = document.getElementById('table-details-header');
            const listContainer = tableListContainerRef.current;
            const detailsContainer = detailsContainerRef.current;
            const headerPathElement = headerLinePathRef.current;
            const rowLinesGroup = rowLinesGroupRef.current;

            // Clear existing paths first
            if (headerPathElement) headerPathElement.setAttribute('d', '');
            if (rowLinesGroup) rowLinesGroup.innerHTML = '';

            if (startElement && listContainer && detailsContainer && window.innerWidth >= 768) {
                const startRect = startElement.getBoundingClientRect();
                const listContainerRect = listContainer.getBoundingClientRect();
                const detailsContainerRect = detailsContainer.getBoundingClientRect();

                const x1 = listContainerRect.right;
                const y1 = startRect.top + startRect.height / 2;
                const x2 = detailsContainerRect.left;

                // Define a single, shared turning point for all lines.
                const intermediateX = x1 + (x2 - x1) / 2;
                
                // 1. Draw header line (if header is visible)
                if (endHeaderElement && headerPathElement) {
                    const endHeaderRect = endHeaderElement.getBoundingClientRect();
                    const y2_header = endHeaderRect.top + endHeaderRect.height / 2;
                    const headerPathData = `M ${x1} ${y1} H ${intermediateX} V ${y2_header} H ${x2}`;
                    headerPathElement.setAttribute('d', headerPathData);
                }
                
                // 2. Draw row lines (if rows are visible)
                if (rowLinesGroup) {
                    for (let i = 0; i < 5; i++) { // Max 5 rows
                        const endRowElement = document.getElementById(`details-row-${i}`);
                        if (endRowElement) {
                            const endRowRect = endRowElement.getBoundingClientRect();
                            const y2_row = endRowRect.top + endRowRect.height / 2;
                            
                            // Use the shared intermediateX for the row path
                            const rowPathData = `M ${x1} ${y1} H ${intermediateX} V ${y2_row} H ${x2}`;
                            
                            // Create and append path element imperatively
                            const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
                            path.setAttribute('d', rowPathData);
                            path.setAttribute('stroke', 'var(--success)');
                            path.setAttribute('stroke-width', '2');
                            path.setAttribute('fill', 'none');
                            path.setAttribute('stroke-linecap', 'round');
                            path.classList.add('connecting-line');
                            rowLinesGroup.appendChild(path);
                        }
                    }
                }
            }
        };

        // Throttle updates using requestAnimationFrame for smooth scrolling
        let isTicking = false;
        const scrollHandler = () => {
            if (!isTicking) {
                window.requestAnimationFrame(() => {
                    updateConnectingLines();
                    isTicking = false;
                });
                isTicking = true;
            }
        };

        // Delay initial calculation to ensure DOM is ready
        const timeoutId = setTimeout(updateConnectingLines, 100);
        const mainElement = document.querySelector('main');

        window.addEventListener('resize', updateConnectingLines);
        mainElement?.addEventListener('scroll', scrollHandler);

        return () => {
            clearTimeout(timeoutId);
            window.removeEventListener('resize', updateConnectingLines);
            mainElement?.removeEventListener('scroll', scrollHandler);
        };
    }, [selectedTable, tableDetails, isFetchingDetails, selectedView]);


    useEffect(() => {
        if (selectedView !== 'db' || !selectedTableInfo) {
            setTableDetails(null);
            return;
        }

        const getDetails = async () => {
            setIsFetchingDetails(true);
            setTableDetails(null); 
            const { data, error } = await fetchTableDetails(selectedTableInfo.name, selectedTableInfo.dbName);
            if (error) {
                console.error(`Failed to fetch details for ${selectedTableInfo.name}`, error);
                alert(`Could not load details for table: ${selectedTableInfo.name}`);
            } else {
                setTableDetails(data);
            }
            setIsFetchingDetails(false);
        };

        getDetails();
    }, [selectedTable, selectedView]);
    
    const handleResetSequenceClick = (tableName: string) => {
        setModal({ type: 'sequence', tableName });
    };

    const handleResetDataClick = (tableName: string) => {
        setModal({ type: 'data', tableName });
        setConfirmationInput('');
    };
    
    const closeModal = () => {
        setModal({ type: null, tableName: null });
        setConfirmationInput('');
    };

    const handleConfirmReset = async () => {
        if (!modal.tableName || !selectedTableInfo) return;
        
        setIsLoading(true);
        try {
            let error;
            const isAgentTable = selectedTableInfo.dbName === 'Agent';

            if (modal.type === 'sequence') {
                ({ error } = isAgentTable 
                    ? await resetAgentTableSequence(modal.tableName) 
                    : await resetTableSequence(modal.tableName));
            } else if (modal.type === 'data') {
                ({ error } = isAgentTable
                    ? await resetAgentTableData(modal.tableName)
                    : await resetTableData(modal.tableName));
            }

            if (error) throw error;
            
            if (modal.type === 'sequence') {
                alert(`Success! The ID sequence for '${modal.tableName}' has been reset. The next entry will start from 1.`);
            } else if (modal.type === 'data') {
                alert(`Success! ALL data from '${modal.tableName}' has been permanently deleted.`);
            }
        } catch (error: any) {
            console.error(`Failed to perform ${modal.type} reset for ${modal.tableName}:`, error);
            // FIX: Provide a more detailed and helpful error message in the alert.
            let errorMessage = `Failed to perform ${modal.type} reset for '${modal.tableName}'.`;
            if (error.message) {
                errorMessage += `\n\nError: ${error.message}`;
            }
            if (error.details) {
                errorMessage += `\nDetails: ${error.details}`;
            }
            if (error.code === '42501' || (error.message && error.message.includes('permission denied'))) {
                const functionName = modal.type === 'data' ? `truncate_table_${modal.tableName}` : `reset_${modal.tableName}_id_sequence`;
                errorMessage += `\n\nHint: This is a permission error (403 Forbidden). The database is blocking the request.\n\nTo fix this, please run the GRANT command for the '${functionName}' function in your Supabase SQL Editor.`;
            } else {
                errorMessage += `\n\nHint: Please check the browser console for the full error object. This could be a network issue or a problem with the Supabase function itself.`;
            }
            alert(errorMessage);
        } finally {
            setIsLoading(false);
            closeModal();
        }
    };
    
    const renderDbManagementView = () => (
        <>
            <style>{`
                .connecting-line {
                    stroke-dasharray: 6 3;
                    animation: march 1s linear infinite;
                    opacity: 0.8;
                }
                @keyframes march {
                    to {
                        stroke-dashoffset: -9;
                    }
                }
            `}</style>
            <svg className="hidden md:block fixed top-0 left-0 w-full h-full pointer-events-none z-10">
                <path
                    ref={headerLinePathRef}
                    stroke="var(--success)"
                    strokeWidth="2"
                    fill="none"
                    className="connecting-line"
                    strokeLinecap="round"
                />
                <g ref={rowLinesGroupRef}></g>
            </svg>
            <div className="flex flex-col md:flex-row gap-8">
                {/* --- Left Sidebar: Database Navigator --- */}
                <aside className="w-full md:w-1/3 lg:w-1/4 xl:w-1/5 shrink-0">
                    <div ref={tableListContainerRef} className="p-4 rounded-lg bg-[var(--card-bg)] border border-[var(--border-color)] sticky top-24">
                        {databases.map(dbGroup => (
                            <div key={dbGroup.dbName} className="mb-6 last:mb-0">
                                <h3 className="flex items-center gap-2 font-bold text-lg text-slate-800 mb-3 px-2">
                                    <Database size={16} />
                                    {dbGroup.dbName}
                                </h3>
                                <div className="space-y-1">
                                    {dbGroup.tables.map(table => (
                                        <div 
                                            key={table.name}
                                            ref={selectedTable === table.name ? selectedTableRef : null}
                                            className={`group w-full flex items-center justify-between p-2 rounded-md transition-colors cursor-pointer ${
                                                selectedTable === table.name
                                                    ? 'bg-indigo-100 dark:bg-indigo-900/20'
                                                    : 'hover:bg-[var(--sidebar-link-hover-bg)]'
                                            }`}
                                            onClick={() => setSelectedTable(table.name)}
                                        >
                                            <div
                                                className={`flex-grow text-left flex items-center gap-2.5 text-sm font-medium ${
                                                    selectedTable === table.name 
                                                        ? 'text-indigo-600 dark:text-indigo-400' 
                                                        : 'text-[var(--sidebar-text-secondary)] group-hover:text-[var(--sidebar-text-primary)]'
                                                }`}
                                            >
                                                <Table size={14} className="shrink-0" />
                                                <span className="truncate font-mono">{table.name}</span>
                                            </div>
                                            <button
                                                onClick={(e) => { e.stopPropagation(); setActivePopover({ tableName: table.name, anchorEl: e.currentTarget }); }}
                                                className={`p-1 rounded-md shrink-0 ${
                                                    selectedTable === table.name
                                                        ? 'text-indigo-600 dark:text-indigo-400'
                                                        : 'text-[var(--sidebar-text-secondary)] opacity-0 group-hover:opacity-100'
                                                }`}
                                                aria-label={`More options for ${table.name}`}
                                            >
                                                <MoreVertical size={16} />
                                            </button>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </aside>

                {/* --- Right Panel: Management Area --- */}
                <main className="flex-1">
                    {isFetchingDetails ? (
                        <PanelCard ref={detailsContainerRef}>
                            <div className="flex flex-col items-center justify-center h-96">
                                <span className="loader"></span>
                                <p className="mt-4 text-slate-500 font-medium">Fetching details for <span className="font-mono">{selectedTable}</span>...</p>
                            </div>
                        </PanelCard>
                    ) : tableDetails ? (
                        <TableDetailsView ref={detailsContainerRef} details={tableDetails} description={selectedTableInfo?.description || ''} />
                    ) : selectedTableInfo ? (
                        <PanelCard ref={detailsContainerRef}>
                            <div className="text-center py-10">
                                <AlertTriangle className="mx-auto h-12 w-12 text-red-400" />
                                <h3 className="mt-2 text-lg font-medium text-slate-800">Failed to Load Details</h3>
                                <p className="mt-1 text-sm text-slate-500">
                                Could not fetch details for the table <strong className="font-mono">{selectedTableInfo.name}</strong>. Please check the console for errors.
                                </p>
                            </div>
                        </PanelCard>
                    ) : (
                        <PanelCard ref={detailsContainerRef}>
                            <p className="text-slate-500 text-center py-10">Select a table from the left to manage it.</p>
                        </PanelCard>
                    )}
                </main>
            </div>
        </>
    );

    return (
        <div className="space-y-6">
            <div className="pill-nav-container">
                <div className="pill-nav">
                    <button onClick={() => setSelectedView('db')} className={`pill-nav-item ${selectedView === 'db' ? 'active' : ''}`}>Database Management</button>
                    <button onClick={() => setSelectedView('keys')} className={`pill-nav-item ${selectedView === 'keys' ? 'active' : ''}`}>AI API Keys</button>
                </div>
            </div>

            {selectedView === 'db' ? renderDbManagementView() : <ApiKeyManagerCard />}

            {activePopover && (
                <ActionPopover
                    anchorEl={activePopover.anchorEl}
                    onClose={() => setActivePopover(null)}
                >
                    {!allTables.find(t => t.name === activePopover.tableName)?.disableSequenceReset && (
                        <button 
                            onClick={() => { handleResetSequenceClick(activePopover.tableName); setActivePopover(null); }}
                            className="custom-dropdown-option !flex items-center gap-2 text-amber-600 dark:text-amber-400 hover:!bg-amber-50 dark:hover:!bg-amber-900/50"
                        >
                            <RefreshCw size={14} /> Reset ID Sequence
                        </button>
                    )}
                    <button 
                        onClick={() => { handleResetDataClick(activePopover.tableName); setActivePopover(null); }}
                        className="custom-dropdown-option !flex items-center gap-2 text-red-600 dark:text-red-400 hover:!bg-red-50 dark:hover:!bg-red-900/50"
                    >
                        <Trash2 size={14} /> Delete All Data...
                    </button>
                </ActionPopover>
            )}

            {/* Modal for Reset IDs */}
            <ConfirmationModal
                isOpen={modal.type === 'sequence'}
                onClose={closeModal}
                onConfirm={handleConfirmReset}
                title="Reset ID Sequence"
                message={
                    <div className="space-y-3">
                        <div className="flex items-start gap-3 p-3 bg-yellow-50 dark:bg-yellow-900/30 border border-yellow-200 dark:border-yellow-800/50 rounded-md">
                            <AlertTriangle className="w-8 h-8 text-yellow-500 shrink-0" />
                            <p className="text-sm text-yellow-800 dark:text-yellow-200">
                                Are you sure you want to reset the IDs for the <strong>{modal.tableName}</strong> table? The next new row will get ID 1.
                            </p>
                        </div>
                    </div>
                }
                confirmText={isLoading ? "Resetting..." : "Confirm Reset"}
                confirmButtonClass="btn-danger-secondary"
                isConfirmDisabled={isLoading}
            />
            
            {/* Modal for Reset Data */}
             <ConfirmationModal
                isOpen={modal.type === 'data'}
                onClose={closeModal}
                onConfirm={handleConfirmReset}
                title="Permanently Delete Table Data"
                message={
                    <div className="space-y-4">
                        <div className="flex items-start gap-3 p-4 bg-red-50 dark:bg-red-950/60 border border-red-200 dark:border-red-800 rounded-lg">
                            <AlertTriangle className="w-12 h-12 text-red-500 shrink-0 mt-1" />
                            <div>
                                <h4 className="font-bold text-red-900 dark:text-red-200">Irreversible Action</h4>
                                <p className="text-sm text-red-800 dark:text-red-200">
                                    This will permanently delete <strong>ALL</strong> data from the <strong className="font-mono">{modal.tableName}</strong> table.
                                </p>
                            </div>
                        </div>
                        <p>To proceed, please type the name of the table (<strong className="font-mono">{modal.tableName}</strong>) in the box below.</p>
                        <input
                            type="text"
                            value={confirmationInput}
                            onChange={(e) => setConfirmationInput(e.target.value)}
                            className="form-input w-full mt-1 font-mono"
                            autoFocus
                        />
                    </div>
                }
                confirmText={isLoading ? "Deleting..." : "Permanently Delete"}
                confirmButtonClass="btn-danger"
                isConfirmDisabled={isLoading || confirmationInput !== modal.tableName}
            />
        </div>
    );
};

export default SettingsPage;