import React, { useState, useEffect } from 'react';
import { PanelCard, ConfirmationModal } from '../components/ui';
import { resetTableSequence, resetTableData, resetAgentTableSequence, resetAgentTableData } from '../services/dataManagementService';
import { Database, AlertTriangle, RefreshCw, Trash2, Table, X } from 'lucide-react';

interface TableInfo {
    name: string;
    description: string;
    disableSequenceReset?: boolean;
}

interface DatabaseGroup {
    dbName: 'Main App' | 'Agent';
    tables: TableInfo[];
}

const databases: DatabaseGroup[] = [
    {
        dbName: 'Main App',
        tables: [
            { name: 'profiles', description: "Core user profile information, linked to authentication.", disableSequenceReset: true },
            { name: 'conversations', description: "Primary storage for all user conversations with the AI.", disableSequenceReset: true },
            { name: 'ltm', description: "Stores long-term memory facts generated by the AI for each user.", disableSequenceReset: true },
            { name: 'code_memory', description: "Stores code snippets saved by users during conversations.", disableSequenceReset: true },
            { name: 'user_article_interactions', description: "Tracks user likes, views, and bookmarks on news articles.", disableSequenceReset: true },
            { name: 'user_settings', description: "Contains individual user preferences and configurations.", disableSequenceReset: true },
            { name: 'public_news_articles', description: "The main table for all published and user-visible news articles." },
            { name: 'public_article_cache', description: "Stores cached article content to speed up retrieval.", disableSequenceReset: true },
            { name: 'article_conversations', description: "Links conversations to specific news articles that were discussed.", disableSequenceReset: true },
            { name: 'update_news_logs', description: "Logs for the periodic 'update_news' function runs." },
        ]
    },
    {
        dbName: 'Agent',
        tables: [
            { name: 'groq_agent_logs', description: "Logs for the Groq agent function runs." },
        ]
    }
];

const SettingsPage: React.FC = () => {
    const [selectedTable, setSelectedTable] = useState('profiles');
    const [modal, setModal] = useState<{ type: 'sequence' | 'data' | null; tableName: string | null }>({ type: null, tableName: null });
    const [isLoading, setIsLoading] = useState(false);
    const [confirmationInput, setConfirmationInput] = useState('');
    
    // State for the new armed action mechanism
    const [armedAction, setArmedAction] = useState<'sequence' | 'data' | null>(null);
    const [countdown, setCountdown] = useState(3);


    const allTables = databases.flatMap(db => db.tables.map(t => ({ ...t, dbName: db.dbName })));
    const selectedTableInfo = allTables.find(t => t.name === selectedTable);
    const canResetSequence = selectedTableInfo && !selectedTableInfo.disableSequenceReset;


    // Countdown timer effect
    useEffect(() => {
        if (!armedAction) return;
        if (countdown === 0) return;

        const timerId = setTimeout(() => {
            setCountdown(countdown - 1);
        }, 1000);

        return () => clearTimeout(timerId);
    }, [armedAction, countdown]);

    const handleArmAction = (actionType: 'sequence' | 'data') => {
        setCountdown(3);
        setArmedAction(actionType);
    };
    
    const handleDisarmAction = () => {
        setArmedAction(null);
    };

    const handleResetSequenceClick = (tableName: string) => {
        setModal({ type: 'sequence', tableName });
    };

    const handleResetDataClick = (tableName: string) => {
        setModal({ type: 'data', tableName });
        setConfirmationInput('');
    };
    
    const closeModal = () => {
        setModal({ type: null, tableName: null });
        setConfirmationInput('');
        handleDisarmAction(); // Also disarm on modal close
    };

    const handleConfirmReset = async () => {
        if (!modal.tableName || !selectedTableInfo) return;
        
        setIsLoading(true);
        try {
            let error;
            const isAgentTable = selectedTableInfo.dbName === 'Agent';

            if (modal.type === 'sequence') {
                ({ error } = isAgentTable 
                    ? await resetAgentTableSequence(modal.tableName) 
                    : await resetTableSequence(modal.tableName));
            } else if (modal.type === 'data') {
                ({ error } = isAgentTable
                    ? await resetAgentTableData(modal.tableName)
                    : await resetTableData(modal.tableName));
            }

            if (error) throw error;
            
            if (modal.type === 'sequence') {
                alert(`Success! The ID sequence for '${modal.tableName}' has been reset. The next entry will start from 1.`);
            } else if (modal.type === 'data') {
                alert(`Success! ALL data from '${modal.tableName}' has been permanently deleted.`);
            }
        } catch (error: any) {
            console.error(`Failed to perform ${modal.type} reset for ${modal.tableName}:`, error);
            
            const dbErrorMessage = error?.details || error?.message || 'An unexpected error occurred.';
            let userFriendlyMessage = `Failed to perform ${modal.type} reset for '${modal.tableName}'.\n\n`;

            if (dbErrorMessage.includes('does not exist')) {
                if (dbErrorMessage.includes('function')) {
                    userFriendlyMessage += `Reason: The required database function for this action was not found.\n\nPlease ensure you have created the correct function (e.g., 'reset_${modal.tableName}_id_sequence') in the Supabase SQL Editor.`;
                } else {
                    userFriendlyMessage += `Database Error: ${dbErrorMessage}\n\nThis can happen if the table's primary key column is not a standard auto-incrementing 'id'.`;
                }
            } else if (dbErrorMessage.includes('No sequence found for table')) {
                userFriendlyMessage += `Reason: ${dbErrorMessage}\n\nPlease check that the primary key column is named 'id' and is an auto-incrementing type.`;
            } else {
                userFriendlyMessage += `Database Error: ${dbErrorMessage}`;
            }

            alert(userFriendlyMessage);
        } finally {
            setIsLoading(false);
            closeModal();
        }
    };
    
    const ActionCard: React.FC<{
        title: string,
        description: string,
        actionType: 'sequence' | 'data',
    }> = ({ title, description, actionType }) => {
        const isArmed = armedAction === actionType;
        const isCountdownActive = isArmed && countdown > 0;
        const confirmHandler = actionType === 'sequence' 
            ? () => handleResetSequenceClick(selectedTableInfo!.name)
            : () => handleResetDataClick(selectedTableInfo!.name);
            
        const buttonText = actionType === 'sequence' ? 'Arm Action' : 'Arm Deletion';
        const buttonIcon = actionType === 'sequence' ? <RefreshCw size={16} /> : <Trash2 size={16} />;

        return (
            <div className="bg-zinc-800/50 dark:bg-zinc-900/70 border border-zinc-700/50 dark:border-zinc-700 p-4 rounded-lg flex flex-col justify-between items-start gap-4">
                <div>
                    <h4 className="font-semibold text-slate-800 dark:text-zinc-200">{title}</h4>
                    <p className="text-sm text-slate-600 dark:text-zinc-400 mt-1 max-w-md">{description}</p>
                </div>
                <div className="flex items-center justify-end gap-3 w-full shrink-0">
                    {isArmed ? (
                        <>
                            <button
                                onClick={confirmHandler}
                                className={`btn btn-danger justify-center ${!isCountdownActive ? 'animate-pulse-danger' : ''}`}
                                disabled={isCountdownActive}
                            >
                                {isCountdownActive ? (
                                    <span className="font-mono">Confirm in T-{countdown}s</span>
                                ) : (
                                    <><AlertTriangle size={16} /> Confirm</>
                                )}
                            </button>
                            <button onClick={handleDisarmAction} className="btn btn-secondary !p-2.5" aria-label="Cancel">
                                <X size={16} />
                            </button>
                        </>
                    ) : (
                        <button 
                            onClick={() => handleArmAction(actionType)}
                            className={`btn ${actionType === 'sequence' ? 'btn-danger-secondary' : 'btn-danger'} justify-center`}
                            disabled={armedAction !== null}
                        >
                            {buttonIcon} {buttonText}
                        </button>
                    )}
                </div>
            </div>
        );
    };

    return (
        <>
            <div className="flex flex-col md:flex-row gap-8">
                {/* --- Left Sidebar: Database Navigator --- */}
                <aside className="w-full md:w-1/3 lg:w-1/4 xl:w-1/5 shrink-0">
                    <div className="p-4 rounded-lg bg-[var(--card-bg)] border border-[var(--border-color)] sticky top-24">
                        {databases.map(dbGroup => (
                            <div key={dbGroup.dbName} className="mb-6 last:mb-0">
                                <h3 className="flex items-center gap-2 font-bold text-lg text-slate-800 mb-3 px-2">
                                    <Database size={16} />
                                    {dbGroup.dbName}
                                </h3>
                                <div className="space-y-1">
                                    {dbGroup.tables.map(table => (
                                        <button 
                                            key={table.name}
                                            onClick={() => {
                                                setSelectedTable(table.name);
                                                handleDisarmAction();
                                            }}
                                            className={`w-full text-left flex items-center gap-2.5 p-2 rounded-md text-sm font-medium transition-colors ${
                                                selectedTable === table.name
                                                    ? 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-300'
                                                    : 'text-slate-600 hover:bg-slate-100 hover:text-slate-800 dark:text-zinc-400 dark:hover:bg-zinc-700 dark:hover:text-zinc-200'
                                            }`}
                                        >
                                            <Table size={14} className="shrink-0" />
                                            <span className="truncate font-mono">{table.name}</span>
                                        </button>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </aside>

                {/* --- Right Panel: Management Area --- */}
                <main className="flex-1">
                    {selectedTableInfo ? (
                        <PanelCard>
                            <div className="border-b border-slate-200 pb-4 mb-6">
                                <h2 className="text-2xl font-bold text-slate-800 font-mono">{selectedTableInfo.name}</h2>
                                <p className="text-sm text-slate-500 mt-1">{selectedTableInfo.description}</p>
                            </div>
                            
                            <div className="bg-zinc-900/5 rounded-lg p-6 dark:bg-zinc-900/30 border border-zinc-500/10 dark:border-zinc-700/50">
                                <div className="flex items-center gap-3">
                                    <AlertTriangle className="w-6 h-6 text-red-600 dark:text-red-500" />
                                    <h3 className="text-xl font-bold text-red-800 dark:text-red-300">Danger Zone</h3>
                                </div>
                                <p className="text-sm text-red-700 mt-2 mb-6 ml-9 dark:text-red-400">
                                    These actions are irreversible and can lead to data loss. Be absolutely certain before proceeding.
                                </p>
                                
                                <div className={`grid grid-cols-1 ${canResetSequence ? 'sm:grid-cols-2' : ''} gap-4`}>
                                    {canResetSequence && (
                                        <ActionCard 
                                            title="Reset ID Sequence"
                                            description="Resets the table's primary key sequence. The next new row will have an ID of 1."
                                            actionType="sequence"
                                        />
                                    )}
                                    <ActionCard 
                                        title="Delete All Table Data"
                                        description="Permanently deletes all rows from this table. This cannot be undone."
                                        actionType="data"
                                    />
                                </div>
                            </div>
                        </PanelCard>
                    ) : (
                        <PanelCard>
                            <p className="text-slate-500 text-center py-10">Select a table from the left to manage it.</p>
                        </PanelCard>
                    )}
                </main>
            </div>

            {/* Modal for Reset IDs */}
            <ConfirmationModal
                isOpen={modal.type === 'sequence'}
                onClose={closeModal}
                onConfirm={handleConfirmReset}
                title="Confirm ID Reset"
                message={
                    <div className="space-y-3">
                        <div className="flex items-start gap-3 p-3 bg-yellow-50 border border-yellow-300 rounded-md dark:bg-yellow-900/30 dark:border-yellow-700">
                            <AlertTriangle className="w-8 h-8 text-yellow-500 shrink-0" />
                            <p className="text-sm text-yellow-800 dark:text-yellow-200">
                                This is a potentially destructive action. Are you sure you want to reset the IDs for the <strong>{modal.tableName}</strong> table?
                            </p>
                        </div>
                         <p>The next entry created will have an ID of 1. This can affect data relationships if foreign keys are not handled carefully.</p>
                    </div>
                }
                confirmText={isLoading ? "Resetting..." : "I understand, reset IDs"}
                confirmButtonClass="btn-danger"
                isConfirmDisabled={isLoading}
            />
            
            {/* Modal for Reset Data */}
             <ConfirmationModal
                isOpen={modal.type === 'data'}
                onClose={closeModal}
                onConfirm={handleConfirmReset}
                title="EXTREME DANGER: Confirm Data Deletion"
                message={
                    <div className="space-y-4">
                        <div className="flex items-start gap-3 p-3 bg-red-100 border border-red-300 rounded-md dark:bg-red-900/30 dark:border-red-700">
                            <AlertTriangle className="w-12 h-12 text-red-500 shrink-0" />
                            <p className="text-sm text-red-800 dark:text-red-200">
                                This action will permanently delete <strong>ALL</strong> data from the <strong className="font-mono">{modal.tableName}</strong> table. This cannot be undone.
                            </p>
                        </div>
                        <p>To proceed, please type the name of the table (<strong className="font-mono">{modal.tableName}</strong>) in the box below.</p>
                        <input
                            type="text"
                            value={confirmationInput}
                            onChange={(e) => setConfirmationInput(e.target.value)}
                            className="form-input w-full mt-3 font-mono"
                            autoFocus
                        />
                    </div>
                }
                confirmText={isLoading ? "Deleting..." : "Permanently Delete Data"}
                confirmButtonClass="btn-danger"
                isConfirmDisabled={isLoading || confirmationInput !== modal.tableName}
            />
        </>
    );
};

export default SettingsPage;